# deploy.yml

name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ] # Trigger the action on push to the main branch
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Firebase Config
        run: |
          touch firebase-config.js
          echo "const firebaseConfig = {" >> firebase-config.js
          echo "  apiKey: \"${{ secrets.VITE_API_KEY }}\"," >> firebase-config.js
          echo "  authDomain: \"${{ secrets.VITE_AUTH_DOMAIN }}\"," >> firebase-config.js
          echo "  projectId: \"${{ secrets.VITE_PROJECT_ID }}\"," >> firebase-config.js
          echo "  storageBucket: \"${{ secrets.VITE_STORAGE_BUCKET }}\"," >> firebase-config.js
          echo "  messagingSenderId: \"${{ secrets.VITE_MESSAGING_SENDER_ID }}\"," >> firebase-config.js
          echo "  appId: \"${{ secrets.VITE_APP_ID }}\"," >> firebase-config.js
          echo "  measurementId: \"${{ secrets.VITE_MEASUREMENT_ID }}\"" >> firebase-config.js
          echo "};" >> firebase-config.js

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
